# frozen_string_literal: true

source "https://rubygems.org"

#gem "jekyll", "~> 3.9"
#gem "just-the-docs"

gem "github-pages", group: :jekyll_plugins
gem "just-the-docs"

gem "kramdown"
gem "kramdown-parser-gfm"
#git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
